### ISSUE TITLE
deploy to bluemix fails during repository cloning 

### ISSUE THREAD

**Issue by sjfink** [watson-developer-cloud/natural-language-understanding-nodejs#4]
Screenshot attached.
<img width="778" alt="screen shot 2017-04-13 at 11 00 39 am" src="https://cloud.githubusercontent.com/assets/1533170/25010613/a9c63f0a-2038-11e7-862f-f5d286c9650d.png">

**Comment by germanattanasio** [comment]
We need to switch to use the new [Bluemix devops](https://console.ng.bluemix.net/devops/setup/deploy?repository=https://github.com/watson-developer-cloud/natural-language-understanding-nodejs) process. In the meantime you can follow the instructions to deploy the demo from a local environment.
I'm going to remove the deploy to bluemix button

**Comment by germanattanasio** [comment]
button removed in https://github.com/watson-developer-cloud/natural-language-understanding-nodejs/commit/9b500f0e3effd4203c9435cf2202bbea2bd0ba72

**Comment by germanattanasio** [comment]
Fixed in #14
